# Site Settings
title: Game Production Portfolio
author: Andrew J Webster
email: AndrewJWebster1981@gmail.com

# Build settings
theme: minima
markdown: kramdown

# GitHub Pages settings
baseurl: "/Career"
url: "https://ajwebste1981.github.io"

# Social profiles
linkedin_username: andrew-j-webster-4b0b7b1b3
github_username: ajwebste1981

# Additional settings
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Header customization

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  toc_levels: 1..3
